### ISSUE TITLE
API token invalid message when syncing within logseq

### ISSUE THREAD

**Issue by ChlupacTheBosmer** [b-yp/logseq-notion-sync#13]
Hi,

I installed the plugin and followed the set-up instructions. I created a new internal integration in Notion and pasted the secret code into the plugin settings. I copied and formatted page-id and pasted it into the plug-in settings. I also added the connection to the specific page in Notion.

Issue: When trying to /sync a page or block I get an error message that the API token is invalid. I have tried many things trying to fix it but no change.

Would you happen to have any suggestions? Does the Notion integration have to be made public? 

Thank you.

**Comment by b-yp** [comment]
Thank you for bringing up the issue. Notion integration doesn't need to be set to public. Based on your description, it seems like it could be an issue with the integrations. You can delete the integrations and generate a new one. Follow the instructions in the README to set it up again. It would be even better if you could provide some screenshots as they would help me pinpoint the problem more quickly.

**Comment by drdh** [comment]
I got the same error and restarting Logseq helps solve it.

**Comment by ChlupacTheBosmer** [comment]
I tried restarting and I got the same error, however updating and restarting Logseq has fixed it. Sorry for the delay and for not trying that before. Thanks for your plugin and quick response.

**Comment by b-yp** [comment]
> I tried restarting and I got the same error, however updating and restarting Logseq has fixed it. Sorry for the delay and for not trying that before. Thanks for your plugin and quick response.

Thank you for your reply. Feel free to ask any other questions
