### ISSUE TITLE
Causes Logseq to crash

### ISSUE THREAD

**Issue by richd67** [b-yp/logseq-notion-sync#7]
Every tine I try the sync Logseq page goes blank and is crashed, nothing appears in Notion

**Comment by b-yp** [comment]
It's possible that there is some special formatting in the content of Logseq. Could you please provide a screenshot of the error message when the synchronization fails in Logseq?
You can start by testing the synchronization with a simple example. If it works, then try a more complex one. If it still doesn't work, there might be other issues.

**Comment by richd67** [comment]
Tried with a simple block, same issue. I just get a blank Logseq page it removes everything except the tabs at the top of the page, all menu's and  left sidebar plus any page content gone. No error messages. Only closing and restarting brings it back, thankfully no data loss?
Plus there is nothing transferred to Notion.

**Comment by richd67** [comment]
Just a thought, I note your demo was Mac, could it be different for PC?

**Comment by b-yp** [comment]
Don't worry, your data won't be lost. It should not be related to the operating system. The reason for this issue might be that your API token is invalid. Please check your API token.

**Comment by richd67** [comment]
I used the copy facility when I created the API key and have checked it, it seems fine, exactly the same as in the My Integrations settings

**Comment by richd67** [comment]
Just looking again at the API this was set up as the default 'internal Integration' is that correct?

**Comment by b-yp** [comment]
`Add Connections` , Have you done this step before?

![image](https://github.com/b-yp/logseq-notion-sync/assets/32813227/3b2e9936-e451-4e57-9af0-9557b03b0ab0)

**Comment by richd67** [comment]
So the mistakes I made,
Initially I was trying to add to a table page, this does not seem to work, I think it needs to be a basic page? I had done the Add connection to that page
I then set up a plain page but forgot to do the Add connection step?
When I did it worked.

I was hoping to add a Kanban from Logseq, but I suspect that would be too complicated for this sync?

**Comment by b-yp** [comment]
That's also my question. I didn't write this part in my README document, I will add it later.

It is indeed a bit challenging for synchronization because Logseq doesn't have an official kanban board feature. What kind of content would you like to sync from Logseq to Notion to become a "kanban board"?

**Comment by richd67** [comment]
I have a project were I need to track information about International partners across a number of different stages. The ideal answer would be Logseq multiplayer but not sure how long it will be before that is available. My current system work well for me to track all info and correspondence but I am not able to share it to my team. I have sued Notion before for collaboration so thought your plugin might be the answer.

**Comment by b-yp** [comment]
I think this is challenging.. Even if Logseq can be synced to Notion as a kanban board, collaborative editing can only take place in Notion and cannot be applied to Logseq. In other words, the synchronization is one-way. If you only want others to view the content in Logseq without editing it, you can consider using `publish-spa` (https://github.com/logseq/publish-spa).
